// Generated by CoffeeScript 1.6.2
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["jquery", "underscore", "backbone", "handlebars", "text!app/templates/signup.hbs"], function($, _, Backbone, Handlebars, signupTemplate) {
    'use strict';
    var ContactView, _ref;

    return ContactView = (function(_super) {
      __extends(ContactView, _super);

      function ContactView() {
        this.handleSuccess = __bind(this.handleSuccess, this);        _ref = ContactView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      ContactView.prototype.el = ".content";

      ContactView.prototype.events = {
        "submit #signup-form": "handleSubmit"
      };

      ContactView.prototype.template = Handlebars.compile(signupTemplate);

      ContactView.prototype.initialize = function() {
        return this.render();
      };

      ContactView.prototype.render = function() {
        $(this.el).html(this.template);
        $(".jumbotron").slideDown();
        return $(".jumbotron").removeClass("hidden");
      };

      ContactView.prototype.handleSubmit = function(e) {
        var comments, email, name;

        e.preventDefault();
        if (!($("#user-name").val() && $("#user-email").val())) {
          return alert("Please provide you name and email");
        } else {
          $('input[type="submit"]').attr("disabled", "disabled");
          name = $("#user-name").val();
          email = $("#user-email").val();
          comments = $("#user-comments").val();
          return this.submitForm(name, email, comments);
        }
      };

      ContactView.prototype.submitForm = function(name, email, comments) {
        return $.ajax({
          url: "https://api.mongolab.com/api/1/databases/patience/collections/users?apiKey=nVrJaUBoSsbTUhAJG60sFYya_SB-Kmyu",
          type: "POST",
          data: JSON.stringify({
            "name": name,
            "email": email,
            "comments": comments
          }),
          contentType: "application/json",
          success: this.handleSuccess
        });
      };

      ContactView.prototype.handleSuccess = function(data) {
        return this.options.router.navigate("thanks", {
          trigger: true
        });
      };

      return ContactView;

    })(Backbone.View);
  });

}).call(this);
