// Generated by CoffeeScript 1.6.2
(function() {
  define(["backbone", "./router/router"], function(Backbone, AppRouter) {
    'use strict';
    var BackboneApp;

    return BackboneApp = (function() {
      function BackboneApp() {
        var router;

        router = new AppRouter();
        Backbone.history.start();
      }

      return BackboneApp;

    })();
  });

}).call(this);
