// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["jquery", "backbone", "app/views/about", "app/views/contact", "app/views/home", "app/views/signup", "app/views/thanks"], function($, Backbone, AboutView, ContactView, HomeView, SignupView, ThanksView) {
    var AppRouter, _ref;

    return AppRouter = (function(_super) {
      __extends(AppRouter, _super);

      function AppRouter() {
        _ref = AppRouter.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      AppRouter.prototype.routes = {
        "": "home",
        "about": "about",
        "contact": "contact",
        "home": "home",
        "signup": "signup",
        "thanks": "thanks"
      };

      AppRouter.prototype.home = function() {
        return new HomeView();
      };

      AppRouter.prototype.about = function() {
        return new AboutView();
      };

      AppRouter.prototype.contact = function() {
        return new ContactView();
      };

      AppRouter.prototype.signup = function() {
        return new SignupView({
          router: this
        });
      };

      AppRouter.prototype.thanks = function() {
        return new ThanksView();
      };

      return AppRouter;

    })(Backbone.Router);
  });

}).call(this);
